logging:
  level:
    root: INFO
    org.springframework.security: INFO

jwt:
  key:
    public: classpath:public_key.pem
    private: classpath:private_key.pem
    id: auth-server

# Public client
spring:
  security:
    oauth2:
      authorizationserver:
        client:
          public-client:
            registration:
              client-id: "public-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:4200"
              scopes:
                - "openid"
                - "profile"
                - "read"
                - "write"
              post-logout-redirect-uris:
                - "http://localhost:4200"
            require-authorization-consent: true
            require-proof-key: true